CREATE TABLE entities(
  kind          VARCHAR(32) NOT NULL,
  id            VARCHAR(64) NOT NULL,
  json_data     MEDIUMBLOB NOT NULL,
  json_metadata BLOB NOT NULL,
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(kind, id)
) ENGINE=InnoDB DEFAULT CHARSET='utf8';
